"""Lower exp through __expf when the effective FAST_EXP policy permits it.

FAST_EXP follows the enabled FAST_MATH default; its own explicit pin overrides the umbrella.
The rewrite changes CUDA rounding but preserves the host reference semantics. Half inputs
are promoted for __expf and rounded back afterward. The recorded knob makes the pass idempotent.

This runs after materialization so it also reaches softmax expressions generated by the
fragment realizer, which never pass through Loop IR.
"""

from __future__ import annotations

from dataclasses import replace

from emmy.compiler.graph import Node
from emmy.compiler.ir.elementwise import ElementwiseImpl
from emmy.compiler.ir.kernel import KernelOp
from emmy.compiler.ir.stmt import Body, Stmt
from emmy.compiler.pipeline import Pattern, RuleSkipped
from emmy.compiler.pipeline.search.space import FAST_EXP, precision_pin

PATTERN = [Pattern("root", KernelOp)]

_FAST = ElementwiseImpl("exp_fast")


def rewrite(root: Node) -> KernelOp | None:
    op: KernelOp = root.op
    if FAST_EXP.name in op.knobs:
        raise RuleSkipped("FAST_EXP already decided (idempotence via knob)")
    if not precision_pin(FAST_EXP):
        return replace(op, body=op.body, knobs={**op.knobs, FAST_EXP.name: False})
    new_body, _ = _walk(op.body)
    return replace(op, body=new_body, knobs={**op.knobs, FAST_EXP.name: True})


def _walk(body: Body) -> tuple[Body, bool]:
    stmts: list[Stmt] = []
    changed = False
    for s in body:
        nested = s.nested()
        if nested:
            new_bodies = []
            sub = False
            for b in nested:
                nb, c = _walk(b)
                new_bodies.append(nb)
                sub = sub or c
            if sub:
                s = s.with_bodies(tuple(new_bodies))
                changed = True
        op_attr = getattr(s, "op", None)
        if isinstance(op_attr, ElementwiseImpl) and op_attr.name == "exp":
            s = replace(s, op=_FAST)
            changed = True
        stmts.append(s)
    return Body(tuple(stmts)), changed
